project:
  name: effort_estimation
  # output_dir: data/processed
  output_dir: C:\\Users\\Nicla\\Documents\\ETHZ\\Lifelogging\\Data\\interim\\scai-ncgg\\parsingsim3\\sim_elderly_3\\effort_estimation_output

datasets:
  - name: parsingsim3_sim_elderly3
    imu_wrist:
      # path: data/raw/parsingsim3/sim_elderly_3/corsano_bioz_acc
      path: C:\\Users\\Nicla\\Documents\\ETHZ\\Lifelogging\\Data\\interim\\scai-ncgg\\parsingsim3\\sim_elderly_3\\corsano_wrist_acc\\2025-12-04.csv.gz
      fs_out: 32
    imu_bioz:
      # path: data/raw/parsingsim3/sim_elderly_3/corsano_bioz_acc
      path: C:\\Users\\Nicla\\Documents\\ETHZ\\Lifelogging\\Data\\interim\\scai-ncgg\\parsingsim3\\sim_elderly_3\\corsano_bioz_acc\\2025-12-04.csv.gz
      fs_out: 32
    ecg:
      path: data/raw/parsingsim3/sim_elderly_3/vivalnk_vv330_ecg
      fs: 128

preprocessing:
  imu:
    noise_cutoff: 5.0
    gravity_cutoff: 0.3
    normalise: true

windowing:
  overlap: 0.7
  window_lengths_sec: [10, 5, 2]

features:
  imu:
    modality: imu
    signals:
      - acc_x_dyn
      - acc_y_dyn
      - acc_z_dyn
    feature_set: stat
    safe: true
    njobs: 1

targets:
  imu:
    adl_path: D:\ETHZ\Lifelogging\raw\scai-ncgg\simulation\Sim_3\sim_elderly_3\scai_app\ADLs_1.csv

fusion:
  output_dir: C:\Users\Nicla\Documents\ETHZ\Lifelogging\Data\interim\scai-ncgg\parsingsim3\sim_elderly_3\effort_estimation_output\parsingsim3_sim_elderly3\imu_bioz

  modalities:
    imu: C:\Users\Nicla\Documents\ETHZ\Lifelogging\Data\interim\scai-ncgg\parsingsim3\sim_elderly_3\effort_estimation_output\parsingsim3_sim_elderly3\imu_bioz\imu_aligned_{window_length}.csv

  window_lengths_sec: [10.0, 5.0, 2.0]

logging:
  verbose: true