project:
  name: effort_estimation
  # output_dir: data/processed
  output_dir: /Users/pascalschlegel/data/interim/parsingsim3/sim_elderly3/effort_estimation_output
datasets:
  - name: parsingsim3_sim_elderly3
    imu:
      # path: data/raw/parsingsim3/sim_elderly_3/corsano_bioz_acc
      path: /Users/pascalschlegel/data/interim/parsingsim3/sim_elderly3/corsano_bioz_acc/2025-12-04.csv.gz
      fs_out: 32
    ecg:
      path: data/raw/parsingsim3/sim_elderly_3/vivalnk_vv330_ecg
      fs: 128

preprocessing:
  imu:
    noise_cutoff: 5.0
    gravity_cutoff: 0.3
    normalise: true

windowing:
  overlap: 0.7
  window_lengths_sec: [10]

features:
  imu:
    signals:
      - acc_x_dyn
      - acc_y_dyn
      - acc_z_dyn
    feature_set: stat
    safe: true
    njobs: 1

logging:
  verbose: true