# input: 
# config/training.yaml

dataset:
  imu_features_path: C:\Users\Nicla\Documents\ETHZ\Lifelogging\Data\interim\scai-ncgg\parsingsim3\sim_elderly_3\effort_estimation_output\parsingsim3_sim_elderly3\imu_bioz\fused_features_10.0s.csv

splits:
  column: split
  train: train
  val: val
  test: test
  random_seed: 42

normalisation:
  imu:
    method: standard
    save_to: C:\Users\Nicla\Documents\ETHZ\Lifelogging\Data\interim\scai-ncgg\parsingsim3\sim_elderly_3\effort_estimation_output\parsingsim3_sim_elderly3\imu_bioz_scaler.joblib

# model
model:
  input: C:\Users\Nicla\Documents\ETHZ\Lifelogging\Data\interim\scai-ncgg\parsingsim3\sim_elderly_3\effort_estimation_output\parsingsim3_sim_elderly3\fused_features_scaled.csv
  type: ridge
  parameters:
    alpha: 1.0
  
